[package]
name = "trump"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.53"
rpassword = "7.4.0"
rustyline = "17.0.2"
ssh2 = "0.9.5"

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"
